<a href="https://colab.research.google.com/github/ParhamPishro/Flavonoid/blob/main/3%20Exploratory%20Data%20Analysis/Exploratory_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Read Data

In [17]:
df = pd.read_excel("/content/FlavonoidData.xlsx")
df

,authors,flavonoid,cell line,time,dose,viability-mean,viability-error,viability-SD,viability-SE
0,Chen et al. 2017,Luteolin,KYSE30,48,10.0,77.272727,77.272727,0.001000,NaN
1,Chen et al. 2017,Luteolin,KYSE30,48,20.0,67.613636,67.613636,0.001000,NaN
2,Chen et al. 2017,Luteolin,KYSE30,48,40.0,47.159091,47.159091,0.001000,NaN
3,Chen et al. 2017,Luteolin,KYSE30,48,80.0,32.386364,32.386364,0.001000,NaN
4,Chen et al. 2017,Luteolin,KYSE30,72,10.0,69.886364,69.886364,0.001000,NaN
...,...,...,...,...,...,...,...,...,...
479,Zhu et al. 2016,Apigenin,KYSE150,24,20.0,88.407643,88.407643,0.001000,NaN
480,Zhu et al. 2016,Apigenin,KYSE150,24,40.0,78.980892,82.802548,3.821656,NaN
481,Zhu et al. 2016,Apigenin,KYSE150,24,60.0,67.261146,70.828025,3.566879,NaN
482,Zhu et al. 2016,Apigenin,KYSE150,24,80.0,45.350318,47.643312,2.292994,NaN
483,Zhu et al. 2016,Apigenin,KYSE150,24,100.0,39.490446,41.528662,2.038217,NaN

Discretized Data

In [18]:
df['v01'] = 1
df.loc[df['viability-mean']>50, 'v01'] = 0

In [19]:
df = df.drop(['authors', 'viability-error', 'viability-SD', 'viability-SE', 'v01'], axis=1)
df

    flavonoid cell line  time   dose  viability-mean
0    Luteolin    KYSE30    48   10.0       77.272727
1    Luteolin    KYSE30    48   20.0       67.613636
2    Luteolin    KYSE30    48   40.0       47.159091
3    Luteolin    KYSE30    48   80.0       32.386364
4    Luteolin    KYSE30    72   10.0       69.886364
..        ...       ...   ...    ...             ...
479  Apigenin   KYSE150    24   20.0       88.407643
480  Apigenin   KYSE150    24   40.0       78.980892
481  Apigenin   KYSE150    24   60.0       67.261146
482  Apigenin   KYSE150    24   80.0       45.350318
483  Apigenin   KYSE150    24  100.0       39.490446

[484 rows x 5 columns]

Exploratory Data Analysis (EDA)

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
time,484.0,50.330579,19.053977,24.000000,24.000000,48.00000,72.000000,72.000000
dose,484.0,41.383264,33.629117,1.000000,20.000000,40.00000,63.750000,300.000000
viability-mean,484.0,57.088105,21.670983,1.714286,44.279525,61.07748,73.846554,95.769231